max_steps: -1
max_epochs: -1

defaults:
  - _self_
  - model: paper
  - dataset: dsprites
  - optional model_dataset: ${model}-${dataset}

batch_size: 64
accelerator: null  # from pytorch-lightning, the hardware platform used to train the neural network
devices: null  # the devices to use in a given hardware platform (see argument above)
gradient_clip_val: 0.0  # gradient clip value - set to 0.0 to disable
gradient_clip_algorithm: norm  # gradient clip algorithm - either 'norm' or 'value'
ckpt: null  # path to checkpoint
seed: 1337  # random seed
enable_beta_warmup: false
beta_warmup:
  _target_: .callbacks.beta_warmup.BetaWarmup
  beta_start: 0.0
  beta_end: 1.0
  delta: 0.1
  steps: 5_000

hydra:
  run:
    dir: saved_models/${now:%Y_%m_%d_%H_%M_%S}  # where run train.py it will create under {current working directory}/saved_models a folder with the current date and time and it will be setted as new cwd