# @package _global_
dataset:
  _target_: factor_vae.dataset.dsprites.DSpritesImages
  splits: [0.7, 0.15, 0.15]
  width: 64
  height: 64
  input_channels: 1
  split: train  # train, val or test

max_steps: 300000