# @package _global_
dataset:
  _target_: factor_vae.dataset.dsprites.DSpritesImages
  width: 64
  height: 64
  input_channels: 1
  train_size: 0.85
  download: true
  train: true  # train or test

max_steps: 300000