_target_: factor_vae.model.factor_vae.FactorVAE
d: 10
latent_size: 10
gamma: 6.4
log_freq: 1000
opt_vae:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-4
opt_discriminator:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-4
  betas: [0.5, 0.9]
encoder:
    _target_: factor_vae.model.encoder_decoder.dsprites_encoder
    input_channels: ${dataset.input_channels}
    latent_size: ${model.latent_size}
decoder:
    _target_: factor_vae.model.encoder_decoder.dsprites_decoder
    latent_size: ${model.latent_size}
    output_channels: ${dataset.input_channels}
discriminator:
    _target_: factor_vae.model.discriminator.make_sequential_discriminator
    input_size: ${model.latent_size}
    hidden_size: 1000
    num_hidden_layers: 5