max_steps: -1

defaults:
  - model: paper
  - dataset: dsprites
  - optional model_dataset: ${model}-${dataset}

batch_size: 32
accelerator: null  # from pytorch-lightning, the hardware platform used to train the neural network
devices: null  # the devices to use in a given hardware platform (see argument above)
gradient_clip_val: 0.0  # gradient clip value - set to 0.0 to disable
gradient_clip_algorithm: norm  # gradient clip algorithm - either 'norm' or 'value'
ckpt: null  # path to checkpoint
seed: 1337  # random seed

hydra:
  run:
    dir: saved_models/${now:%Y_%m_%d_%H_%M_%S}  # where run train.py it will create under {current working directory}/saved_models a folder with the current date and time and it will be setted as new cwd